{% set name = "tskit" %}
{% set version = "1.0.1" %}
{% set sha256 = "2bcf811e420d28a52f4994f72cb3b6900d31865ca0deaefce0aec4ee26021581" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tskit=tskit.cli:tskit_main
  skip: true  # [py<39]

# Following the guidance here for building against numpy:
# https://conda-forge.org/docs/meta.html#building-against-numpy
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    # Support for osx_arm64 as per
    # https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - setuptools
    - python
    - pip
    - numpy
  run:
    - python
    - jsonschema

test:
  imports:
    - tskit

  commands:
    - tskit --help

about:
  home: http://github.com/tskit-dev/tskit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The tree sequence toolkit.
  description: Toolkit for storing and processing large-scale genetic genealogies.
  doc_url: https://tskit.dev/tskit/docs
  dev_url: https://github.com/tskit-dev/tskit

extra:
  recipe-maintainers:
    - jeromekelleher
    - benjeffery
    - petrelharp
